name: ships_fitting
channels:
  - conda-forge

dependencies:
  - python=3.10

  # Core
  - numpy
  - pandas
  - scipy
  - libstdcxx-ng

  # Data / utils
  - h5py
  - requests

  # Optional but useful
  - pip

  - pip:
      - mlflow
      - flask
      - gunicorn
      - sqlalchemy
      - alembic
      - gitpython
      - docker
      - haversine
      - tensorflow
      - tabulate
      - tensorboard
