name: ships_processing_2
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # core stack
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - dask
  - distributed

  # plotting / utils
  - matplotlib
  - seaborn
  - tqdm

  # geo (you use basemap / shapely / proj)
  - shapely
  - pyproj
  - geopandas

  # misc
  - requests
  - pyyaml
  - pyarrow
  - pydap
  - pyproj

  # optional but safer modern replacements
  - fsspec

  - pip:
      - debugpy
      - haversine
      - utm